// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VideoUrlParseResponseMessage.proto

package com.stupidbeauty.grebe;

public final class VideoUrlParseResponseMessageProtos {
  private VideoUrlParseResponseMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VideoUrlParseResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stupidbeauty.grebe.VideoUrlParseResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *视频下载网址。
     * </pre>
     *
     * <code>string videoUrl = 1;</code>
     */
    java.lang.String getVideoUrl();
    /**
     * <pre>
     *视频下载网址。
     * </pre>
     *
     * <code>string videoUrl = 1;</code>
     */
    com.google.protobuf.ByteString
        getVideoUrlBytes();

    /**
     * <pre>
     *引荐网址。
     * </pre>
     *
     * <code>string refererUrl = 2;</code>
     */
    java.lang.String getRefererUrl();
    /**
     * <pre>
     *引荐网址。
     * </pre>
     *
     * <code>string refererUrl = 2;</code>
     */
    com.google.protobuf.ByteString
        getRefererUrlBytes();
  }
  /**
   * Protobuf type {@code com.stupidbeauty.grebe.VideoUrlParseResponseMessage}
   */
  public  static final class VideoUrlParseResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stupidbeauty.grebe.VideoUrlParseResponseMessage)
      VideoUrlParseResponseMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VideoUrlParseResponseMessage.newBuilder() to construct.
    private VideoUrlParseResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VideoUrlParseResponseMessage() {
      videoUrl_ = "";
      refererUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VideoUrlParseResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              videoUrl_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              refererUrl_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.internal_static_com_stupidbeauty_grebe_VideoUrlParseResponseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.internal_static_com_stupidbeauty_grebe_VideoUrlParseResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage.class, com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage.Builder.class);
    }

    public static final int VIDEOURL_FIELD_NUMBER = 1;
    private volatile java.lang.Object videoUrl_;
    /**
     * <pre>
     *视频下载网址。
     * </pre>
     *
     * <code>string videoUrl = 1;</code>
     */
    public java.lang.String getVideoUrl() {
      java.lang.Object ref = videoUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        videoUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *视频下载网址。
     * </pre>
     *
     * <code>string videoUrl = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVideoUrlBytes() {
      java.lang.Object ref = videoUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        videoUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERERURL_FIELD_NUMBER = 2;
    private volatile java.lang.Object refererUrl_;
    /**
     * <pre>
     *引荐网址。
     * </pre>
     *
     * <code>string refererUrl = 2;</code>
     */
    public java.lang.String getRefererUrl() {
      java.lang.Object ref = refererUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refererUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *引荐网址。
     * </pre>
     *
     * <code>string refererUrl = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRefererUrlBytes() {
      java.lang.Object ref = refererUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refererUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVideoUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, videoUrl_);
      }
      if (!getRefererUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, refererUrl_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVideoUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, videoUrl_);
      }
      if (!getRefererUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, refererUrl_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage)) {
        return super.equals(obj);
      }
      com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage other = (com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage) obj;

      boolean result = true;
      result = result && getVideoUrl()
          .equals(other.getVideoUrl());
      result = result && getRefererUrl()
          .equals(other.getRefererUrl());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VIDEOURL_FIELD_NUMBER;
      hash = (53 * hash) + getVideoUrl().hashCode();
      hash = (37 * hash) + REFERERURL_FIELD_NUMBER;
      hash = (53 * hash) + getRefererUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stupidbeauty.grebe.VideoUrlParseResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stupidbeauty.grebe.VideoUrlParseResponseMessage)
        com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.internal_static_com_stupidbeauty_grebe_VideoUrlParseResponseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.internal_static_com_stupidbeauty_grebe_VideoUrlParseResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage.class, com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage.Builder.class);
      }

      // Construct using com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        videoUrl_ = "";

        refererUrl_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.internal_static_com_stupidbeauty_grebe_VideoUrlParseResponseMessage_descriptor;
      }

      public com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage getDefaultInstanceForType() {
        return com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage.getDefaultInstance();
      }

      public com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage build() {
        com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage buildPartial() {
        com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage result = new com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage(this);
        result.videoUrl_ = videoUrl_;
        result.refererUrl_ = refererUrl_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage) {
          return mergeFrom((com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage other) {
        if (other == com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage.getDefaultInstance()) return this;
        if (!other.getVideoUrl().isEmpty()) {
          videoUrl_ = other.videoUrl_;
          onChanged();
        }
        if (!other.getRefererUrl().isEmpty()) {
          refererUrl_ = other.refererUrl_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object videoUrl_ = "";
      /**
       * <pre>
       *视频下载网址。
       * </pre>
       *
       * <code>string videoUrl = 1;</code>
       */
      public java.lang.String getVideoUrl() {
        java.lang.Object ref = videoUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          videoUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *视频下载网址。
       * </pre>
       *
       * <code>string videoUrl = 1;</code>
       */
      public com.google.protobuf.ByteString
          getVideoUrlBytes() {
        java.lang.Object ref = videoUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          videoUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *视频下载网址。
       * </pre>
       *
       * <code>string videoUrl = 1;</code>
       */
      public Builder setVideoUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        videoUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *视频下载网址。
       * </pre>
       *
       * <code>string videoUrl = 1;</code>
       */
      public Builder clearVideoUrl() {
        
        videoUrl_ = getDefaultInstance().getVideoUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *视频下载网址。
       * </pre>
       *
       * <code>string videoUrl = 1;</code>
       */
      public Builder setVideoUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        videoUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object refererUrl_ = "";
      /**
       * <pre>
       *引荐网址。
       * </pre>
       *
       * <code>string refererUrl = 2;</code>
       */
      public java.lang.String getRefererUrl() {
        java.lang.Object ref = refererUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          refererUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *引荐网址。
       * </pre>
       *
       * <code>string refererUrl = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRefererUrlBytes() {
        java.lang.Object ref = refererUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          refererUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *引荐网址。
       * </pre>
       *
       * <code>string refererUrl = 2;</code>
       */
      public Builder setRefererUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        refererUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *引荐网址。
       * </pre>
       *
       * <code>string refererUrl = 2;</code>
       */
      public Builder clearRefererUrl() {
        
        refererUrl_ = getDefaultInstance().getRefererUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *引荐网址。
       * </pre>
       *
       * <code>string refererUrl = 2;</code>
       */
      public Builder setRefererUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        refererUrl_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stupidbeauty.grebe.VideoUrlParseResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:com.stupidbeauty.grebe.VideoUrlParseResponseMessage)
    private static final com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage();
    }

    public static com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VideoUrlParseResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<VideoUrlParseResponseMessage>() {
      public VideoUrlParseResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VideoUrlParseResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VideoUrlParseResponseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VideoUrlParseResponseMessage> getParserForType() {
      return PARSER;
    }

    public com.stupidbeauty.grebe.VideoUrlParseResponseMessageProtos.VideoUrlParseResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_grebe_VideoUrlParseResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_grebe_VideoUrlParseResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"VideoUrlParseResponseMessage.proto\022\026co" +
      "m.stupidbeauty.grebe\"D\n\034VideoUrlParseRes" +
      "ponseMessage\022\020\n\010videoUrl\030\001 \001(\t\022\022\n\nrefere" +
      "rUrl\030\002 \001(\tB<\n\026com.stupidbeauty.grebeB\"Vi" +
      "deoUrlParseResponseMessageProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_stupidbeauty_grebe_VideoUrlParseResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_grebe_VideoUrlParseResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_grebe_VideoUrlParseResponseMessage_descriptor,
        new java.lang.String[] { "VideoUrl", "RefererUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
